import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = ({ org }: any) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  
  const response = await fetch('https://api.github.com/orgs/rocketseat');
  const data = await response.json();

  return {
    props: {
      org: data
    }
  }
};

export default Home
